name: Trigger auto deployment for aca-lab-jxyiliu-aca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-lab-jxyiliu-aca-AutoDeployTrigger-dba8e36e-748f-4577-a834-6b7c245684e4.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACALABJXYILIUACA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acalabjxyiliucr.azurecr.io
          registryUsername: ${{ secrets.ACALABJXYILIUACA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACALABJXYILIUACA_REGISTRY_PASSWORD }}
          containerAppName: aca-lab-jxyiliu-aca
          resourceGroup: aca-lab-jxyiliu-rg
          imageToBuild: acalabjxyiliucr.azurecr.io/aca-lab-jxyiliu-aca:${{ github.sha }}
          
            

     

